apiVersion: v1
kind: Service
metadata:
  name: nodejs-tutorial-svc
  labels:
    run: nodejs-tutorial-svc
spec:
  # type: LoadBalancer
  ports:
    # - name: http
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
      # nodePort: 30061
  selector:
    app: nodejs-tutorial
