apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gomesh-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: gomesh.ml
      http:
        paths:
          - path: /
            backend:
              serviceName: node-app-service
              servicePort: 80
