apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: mysite.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: 80
