apiVersion: v1
kind: Service
metadata:
  name: testapi
  namespace: default
  labels:
    application: testapi
spec:
  type: NodePort
  selector:
    application: testapi
  ports:
    - port: 8080
      targetPort: 8080
